dist: xenial
language: python
python:
- '3.6'
deploy:
  provider: heroku
  api_key:
    secure: KX96AFFQYJ86EU+kJiDS28EYSDqDiuhAooYZRUjRIu7MR6CESgmosbQTSmvRtaUBr+RXGEgsOhGdtlhLVMBWTkTRTM+NL/P1npyztPEGmPzOayK3K179gqMwq3p4b9auJWc1tnCDpvSJrLddckl9sjIGjKxfgW0XakvC0/Pn5xJNmGwvaVgfBRFR1bSK4O0+xcMv8dbpfwtbDTzEUk9/aDKGnMoshUlzgreVUXq8nypKfoVyRMIavJBnFm9Q3wfVmsO4fUH72hK3hRUjhf+Sfd/Xg/oGyz95UJeI/qDHCKjg0lGhASV2ZR+W1iTvSwYCOTRSlBAUkgW3Nv8dN8SwVOAxc4xAynWW9wCImFdpSnsvnVeC9+rC2OsAOyJr8Liqf/gXExPHr7sKkRQvSmI5LsJDhU4s9/Z0KWs709oC/e6LxoWnZVaK5RRBN5cqDhgYGdK92/2B6C/jShvFnvwUwC3EN16djpZRT8Vfem4J8YrB+hAdTxW1njkcKfkATPT4FRkIa0VpHqxW6rPBBtmKrfg55lxg+IysY0Y0xYoF4m9OHQ9iC5qDpWblCtoQacKvdf3kCBecAGNM2/vajf9ffiqE2eNO7FEklK+B+oQdeeWQwUI1qqgsqA9eO9wNXZ7ER8rpoNsL1X2GxRhDVsO40iMYa2+cd+C81RD2wYGiyzY=
  app: tinkoff-web-wrapper
  on: heroku-github
cache: pip
before_install:
- export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
- pip install -r requirements.txt
script:
- python manage.py test
services:
- redis-server
#- python helloworld/task_queue.py start
