dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

cache: pip
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
script:
  - python manage.py test
  - python helloworld/task_queue.py start